provincial_code: dict[str: str] = {
    # Metro Manila
    'Manila': 'PH-00',
    'Quezon City': 'PH-00',
    'Caloocan': 'PH-00',
    'Las Piñas': 'PH-00',
    'Makati': 'PH-00',
    'Malabon': 'PH-00',
    'Mandaluyong': 'PH-00',
    'Marikina': 'PH-00',
    'Muntinlupa': 'PH-00',
    'Navotas': 'PH-00',
    'Parañaque': 'PH-00',
    'Pasay': 'PH-00',
    'Pasig': 'PH-00',
    'Pateros': 'PH-00',
    'San Juan': 'PH-00',
    'Taguig': 'PH-00',
    'Valenzuela': 'PH-00',

    # Provinces
    'Abra': 'PH-ABR',
    'Agusan del Norte': 'PH-AGN',
    'Agusan del Sur': 'PH-AGS',
    'Aklan': 'PH-AKL',
    'Albay': 'PH-ALB',
    'Antique': 'PH-ANT',
    'Apayao': 'PH-APA',
    'Aurora': 'PH-AUR',
    'Basilan': 'PH-BAS',
    'Bataan': 'PH-BAN',
    'Batanes': 'PH-BTN',
    'Batangas': 'PH-BTG',
    'Benguet': 'PH-BEN',
    'Biliran': 'PH-BIL',
    'Bohol': 'PH-BOH',
    'Bukidnon': 'PH-BUK',
    'Bulacan': 'PH-BUL',
    'Cagayan': 'PH-CAG',
    'Camarines Norte': 'PH-CAN',
    'Camarines Sur': 'PH-CAS',
    'Camiguin': 'PH-CAM',
    'Capiz': 'PH-CAP',
    'Catanduanes': 'PH-CAT',
    'Cavite': 'PH-CAV',
    'Cebu': 'PH-CEB',
    'Davao de Oro': 'PH-COM',
    'Cotabato': 'PH-NCO',
    'Davao del Norte': 'PH-DAV',
    'Davao del Sur': 'PH-DAS',
    'Davao Occidental': 'PH-DVO',
    'Davao Oriental': 'PH-DAO',
    'Dinagat Islands': 'PH-DIN',
    'Eastern Samar': 'PH-EAS',
    'Guimaras': 'PH-GUI',
    'Ifugao': 'PH-IFU',
    'Ilocos Norte': 'PH-ILN',
    'Ilocos Sur': 'PH-ILS',
    'Iloilo': 'PH-ILI',
    'Isabela': 'PH-ISA',
    'Kalinga': 'PH-KAL',
    'La Union': 'PH-LUN',
    'Laguna': 'PH-LAG',
    'Lanao del Norte': 'PH-LAN',
    'Lanao del Sur': 'PH-LAS',
    'Leyte': 'PH-LEY',
    'Maguindanao del Norte': 'PH-MGN',
    'Maguindanao del Sur': 'PH-MGS',
    'Marinduque': 'PH-MAD',
    'Masbate': 'PH-MAS',
    'Misamis Occidental': 'PH-MSC',
    'Misamis Oriental': 'PH-MSR',
    'Mountain Province': 'PH-MOU',
    'Negros Occidental': 'PH-NEC',
    'Negros Oriental': 'PH-NER',
    'Northern Samar': 'PH-NSA',
    'Nueva Ecija': 'PH-NUE',
    'Nueva Vizcaya': 'PH-NUV',
    'Occidental Mindoro': 'PH-MDC',
    'Oriental Mindoro': 'PH-MDR',
    'Palawan': 'PH-PLW',
    'Pampanga': 'PH-PAM',
    'Pangasinan': 'PH-PAN',
    'Quezon': 'PH-QUE',
    'Quirino': 'PH-QUI',
    'Rizal': 'PH-RIZ',
    'Romblon': 'PH-ROM',
    'Samar': 'PH-WSA',
    'Sarangani': 'PH-SAR',
    'Siquijor': 'PH-SIG',
    'Sorsogon': 'PH-SOR',
    'South Cotabato': 'PH-SCO',
    'Southern Leyte': 'PH-SLE',
    'Sultan Kudarat': 'PH-SUK',
    'Sulu': 'PH-SLU',
    'Surigao del Norte': 'PH-SUN',
    'Surigao del Sur': 'PH-SUR',
    'Tarlac': 'PH-TAR',
    'Tawi-Tawi': 'PH-TAW',
    'Zambales': 'PH-ZMB',
    'Zamboanga del Norte': 'PH-ZAN',
    'Zamboanga del Sur': 'PH-ZAS',
    'Zamboanga Sibugay': 'PH-ZSI',
}

metro_manila: list[str] = ['Manila', 'Quezon City', 'Caloocan', 'Las Piñas', 'Makati', 'Malabon', 'Mandaluyong', 'Marikina', 'Muntinlupa', 'Navotas', 'Parañaque',
                           'Pasay', 'Pasig', 'Pateros', 'San Juan', 'Taguig', 'Valenzuela']
large_province: list[str] = ['Cebu', 'Davao del Sur', 'Iloilo', 'Cavite', 'Rizal', 'Bulacan', 'Laguna', 'Batangas', 'Pampanga', 'Zamboanga del Sur', 'Pangasinan']
medium_province: list[str] = ['Negros Occidental', 'Nueva Ecija', 'Quezon', 'Camarines Sur', 'Leyte', 'Isabela', 'Misamis Oriental', 'South Cotabato', 'Palawan',
                              'Zambales', 'Lanao del Norte', 'Benguet', 'Agusan del Norte', 'Bataan', 'Tarlac', 'Bohol', 'La Union']
small_province: list[str] = ['Albay', 'Cagayan', 'Davao del Norte', 'Sulu', 'Sorsogon', 'Capiz', 'Samar',
                             'Davao de Oro', 'Agusan del Sur', 'Ilocos Sur', 'Zamboanga Sibugay','Surigao del Sur', 'Camarines Norte', 'Ifugao',
                             'Misamis Occidental', 'Aklan', 'Antique', 'Ilocos Norte', 'Basilan', 'Surigao del Norte', 'Occidental Mindoro', 'Nueva Vizcaya',
                             'Southern Leyte', 'Davao Occidental', 'Romblon', 'Catanduanes', 'Batanes', 'Camiguin', 'Siquijor', 'Biliran', 'Quirino', 'Kalinga',
                             'Aurora', 'Marinduque', 'Abra', 'Maguindanao del Norte', 'Maguindanao del Sur', 'Oriental Mindoro']
poor_provinces: list[str] = ['Lanao del Sur', 'Apayao', 'Eastern Samar', 'Zamboanga del Norte', 'Davao Oriental', 'Sarangani', 'Negros Oriental', 'Masbate',
                             'Cotabato', 'Northern Samar', 'Bukidnon', 'Sultan Kudarat', 'Tawi-Tawi', 'Dinagat Islands', 'Guimaras', 'Mountain Province']
